### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by joaoneves792** [NickMaev/NVal-Tippy#1]
I am trying to use NVal-Tippy in a Linux environment however the following issue is currently preventing that.

in index.ts you have
`
export { NValTippy } from "./src/nvalTippy";
`

however the src/nvalTippy file is actually

`
./src/nvaltippy.ts
`

linux is case sensitive, this should work on windows, but fails on linux with the following:

`
    ERROR in ./node_modules/nval-tippy/dist/cjs/index.js
    Module not found: Error: Can't resolve './src/nvalTippy' in '/src/node_modules/nval-tippy/dist/cjs'
     @ ./node_modules/nval-tippy/dist/cjs/index.js 3:18-44
`

Could you please fix these lower-case / upper-case inconsistencies?

**Comment by NickMaev** [comment]
Fixed and updated npm package.

**Comment by joaoneves792** [comment]
Thanks a lot!
